version: 2
project_name: ogre

builds:
  - id: ogre
    main: ./cmd/ogre
    binary: ogre
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: wasm
    main: ./cmd/wasm
    binary: ogre
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - js
    goarch:
      - wasm

archives:
  - id: default
    ids:
      - ogre
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: wasm
    ids:
      - wasm
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_wasm"
    files:
      - none*

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))?\!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))?\!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\(.+\))?\!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
